### PR TITLE
Fix non-string map key issues in BSON/JSON protos.

### PR DESCRIPTION
**Pull request by benjyw**
This change:
1. Enforces that map keys are strings.
2. Allows a "coerce" mode in TJSONProtocol where map keys are
    coerced to strings. This is used only in the implementation
    of toString() on records, which just JSON-serialized, and must
    work on all structs, even ones with non-string-key maps.
3. Adds various tests around this.

### CODE REVIEW

**Comment by jliszka** [comment]
Nice! Does this fix the hadoop test that broke with 1.8.0? Were you able to get publish-local to work?

**Comment by benjyw** [comment]
I couldn't get publish local to work, but this should fix that test, as the
error was in toString.

Were you able to fix the other error?

**Comment by jliszka** [comment]
I think so, but without a publish-local, I haven't been able to verify. I
could just publish the snapshot, I suppose, but that's a little gross. Any
word from jsirois on a fix?

On Mon, Mar 10, 2014 at 11:35 AM, Benjy Weinberger <notifications@github.com

> wrote:
> 
> I couldn't get publish local to work, but this should fix that test, as
> the
> error was in toString.
> 
> Were you able to fix the other error?
>

**Comment by benjyw** [comment]
I posted his suggested fix (an edit to our ivysettings.xml) in the asana. I
couldn't try it myself because I can't even get sbt to publish locally in
the Spindle project. It's stuck on PGP issues that I haven't been able to
solve.

But if you look in that asana you should see the details, so maybe you can
try that?

**Pull request merged**
