### PR TITLE
Loosen the access restriction for multiple methods, fields and classes so people could inherit them and override part of the logic

### PR DESCRIPTION
**Pull request by zfy0701**
Here is the rational for this pull request:

in spindle, you guys are relied on the wired_name annotation to serialize and deserialize, which is a good way to solve the problem. However, there is two limitation:
1. more storage are needed for db
2. the bson library would not work with other thrift code generator, such as scrooge.

So the way I want to use is to use the field id as the key when read and write mongodb, e.g

```
struct {
   1: string name
   2: int age
}
```

would be like

```
{1: xxx, 2: 18}
```

 in database, though it's less obvious, sometime you need to reference the thrift file to understand the meaning. but it is robust and enough.

So I need to change the logic of read and write and I don't think directly change BSONReadState and TBSONProtocol is a good idea.Therefore I want to change the access restriction for several fields so I could inherit and override part of the logic.

e.g. here is how I want to read:
https://github.com/lambda-initiative/thriftdao/blob/master/src/main/java/com/lambdai/thriftdao/bson/LBSONReadState.java#L18

and how I write:
https://github.com/lambda-initiative/thriftdao/blob/master/src/main/java/com/lambdai/thriftdao/bson/LTBSONProtocol.java#L47

### CODE REVIEW

**Comment by jliszka** [comment]
If you want this behavior, here are some other workarounds I would try first:
1. Use `(wire_name="1")`, `(wire_name="2")`, etc. annotations on all your fields.
2. Override readFieldBegin and writeFieldBegin in TBSONProtocol, calling the super method with a new TField that has the name field set to the field id (in the case of write) or modifying the result of the call to the super method by returning a new TField that satisfies your requirements (in the case of read).

One issue with this is that all mongodb documents must have a field called _id as the primary key. Unless you special-cased it, you would not be able to read or write this field.

**Comment by zfy0701** [comment]
for 1. I won't consider using annotation because it's too much of syntax overhead. And I'm using scrooge so I don't what to rely on it to parse the annotation correctly.

for 2.
   so this will work, though I don't like the fact you need to create an new TField everytime which increase the GC overhead, it need much less modification.
So I'll go with this, and I'll discuss this later if we have performance issue.

Also I still need at least change the TBSONProtocol.realTransport to protected, because I need write something like:

```
    static TBSONObjectProtocol doCreateBlankProtocol(TTransport trans) {
        LTBSONProtocol ret = new LTBSONProtocol();
        ret.realTransport = trans;
        return ret;
    }
```

and I also need BSONReadState.NO_MORE_FIELDS to be public so I could check the return value of super.readFieldBegin

would you mind me do that or do you have better suggestion?

for 3.
Currently I do need manually strip the _id field when I deserialize from it. In the long term my plan is provide a way to map a field to primary key to _id field as needed.

**Comment by jliszka** [comment]
Sure, we can make `realTransport` protected.

As for `NO_MORE_FIELDS`, you can just check `field.type == TType.STOP`. That's what our calling code does.

**Comment by zfy0701** [comment]
pull request updated.

**Pull request merged**
